using UnityEngine;

public class UserData : MonoBehaviour
{
    //User information
    public string username;
    public string userID; //Equate to the one generated by UGS
    bool completed;

    void Awake(){
        InitVR360Counter();
        InitVR360Conditionals();
        CheckComboConditionals();
        ConfigClaimRewards();
    }
    
    public void InitVR360Counter(){
        PlayerPrefs.SetInt("KCHWaterfrontCounterMax", 2);
        PlayerPrefs.SetInt("TamanPerpaduanCounterMax", 2);
        PlayerPrefs.Save();
    }

    public void InitVR360Conditionals(){
        PlayerPrefs.SetInt("KCHWaterfront1",completed ? 1 : 0);
        PlayerPrefs.SetInt("KCHWaterfront2",completed ? 1 : 0);
        PlayerPrefs.SetInt("KCHWaterfrontComplete",completed ? 1 : 0);
        PlayerPrefs.SetInt("TamanPerpaduan1",completed ? 1 : 0);
        PlayerPrefs.SetInt("TamanPerpaduan2",completed ? 1 : 0);
        PlayerPrefs.SetInt("TamanPerpaduanComplete",completed ? 1 : 0);
        PlayerPrefs.Save();
    }

    public void CheckComboConditionals(){

        int kchWaterfront1 = PlayerPrefs.GetInt("KCHWaterfront1");
        int kchWaterfront2 = PlayerPrefs.GetInt("KCHWaterfront2");
        int kchWaterfrontComplete = PlayerPrefs.GetInt("KCHWaterfrontComplete", 0);
        int tmnPerpaduan1 = PlayerPrefs.GetInt("TamanPerpaduan1");
        int tmnPerpaduan2 = PlayerPrefs.GetInt("TamanPerpaduan2");
        int tmnPerpaduanComplete = PlayerPrefs.GetInt("TamanPerpaduanComplete", 0);

        if(kchWaterfront1 == 1 && kchWaterfront2 == 1){
            PlayerPrefs.SetInt("KCHWaterfrontComplete", 1);
        }

        if(tmnPerpaduan1 == 1 && tmnPerpaduan2 == 1){
            PlayerPrefs.SetInt("TamanPerpaduanComplete", 1);
        }

        PlayerPrefs.Save();
    }

    public void ConfigClaimRewards(){
        PlayerPrefs.SetInt("ClaimKCHWaterfront", completed ? 1 : 0);
        PlayerPrefs.SetInt("ClaimTmnPerpaduan", completed ? 1 : 0);
        PlayerPrefs.Save();
    }
}

